-- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR
# WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV';

SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE >= '2022-11-01'
ORDER BY CAR_ID;

SELECT C.CAR_ID
    , C.CAR_TYPE
    , FLOOR(C.DAILY_FEE * (1 - 0.01 * D.DISCOUNT_RATE) * 30) FEE
FROM CAR_RENTAL_COMPANY_CAR C
    INNER JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상')  D
    ON C.CAR_TYPE = D.CAR_TYPE
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') AND
    NOT EXISTS (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                WHERE END_DATE >= '2022-11-01' AND C.CAR_ID = H.CAR_ID)
    AND FLOOR(C.DAILY_FEE * (1 - 0.01 * D.DISCOUNT_RATE) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
                
# SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 