-- 코드를 입력하세요
# SELECT *
# FROM REST_INFO I
# ORDER BY I.FOOD_TYPE, I.FAVORITES;

# SELECT REST_NAME, MAX(FAVORITES)
# FROM REST_INFO
# WHERE FOOD_TYPE = '일식'

# SELECT I.REST_ID, I.REST_NAME, MAX(I.FAVORITES) FAVOR
#     FROM REST_INFO I
# GROUP BY I.FOOD_TYPE

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
    INNER JOIN (SELECT MAX(I.FAVORITES) FAVOR
        FROM REST_INFO I
        GROUP BY I.FOOD_TYPE) I ON RI.FAVORITES = I.FAVOR
GROUP BY RI.FOOD_TYPE
ORDER BY RI.FOOD_TYPE DESC;
