-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR
    , MONTH(O.SALES_DATE) AS MONTH
    , COUNT(DISTINCT(I.USER_ID)) AS PUCHASED_USERS
    , ROUND(COUNT(DISTINCT(I.USER_ID)) / (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO
                                   WHERE JOINED >= STR_TO_DATE('20210101', '%Y%m%d') AND JOINED < STR_TO_DATE('20220101', '%Y%m%d')), 1) AS PUCHASED_RATIO
FROM USER_INFO I
    INNER JOIN ONLINE_SALE O ON I.USER_ID = O.USER_ID
WHERE I.JOINED >= STR_TO_DATE('20210101', '%Y%m%d') AND I.JOINED < STR_TO_DATE('20220101', '%Y%m%d')
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE);
