-- 코드를 입력하세요
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, SUM(1) AS RECORDS
FROM (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.START_DATE >= '20220801' AND A.START_DATE < '20221101'
GROUP BY A.CAR_ID
HAVING SUM(1) >= 5) B
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C ON B.CAR_ID = C.CAR_ID AND C.START_DATE >= '20220801' AND C.START_DATE < '20221101'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
ORDER BY MONTH, C.CAR_ID DESC;
