-- 코드를 입력하세요
WITH RECURSIVE TBL AS
(SELECT 0 HOUR
    UNION ALL
SELECT HOUR + 1
FROM TBL T
 WHERE HOUR < 23)
SELECT T.HOUR
    , SUM(CASE WHEN O.ANIMAL_ID IS NULL THEN 0
    ELSE 1 END) AS COUNT
FROM TBL T
    LEFT JOIN ANIMAL_OUTS O ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR;