-- 코드를 입력하세요
# SELECT * FROM USED_GOODS_BOARD

SELECT GU.USER_ID, GU.NICKNAME, SUM(GB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD GB
    INNER JOIN USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY GU.USER_ID
HAVING SUM(GB.PRICE) >= 700000
ORDER BY TOTAL_SALES;