-- 코드를 입력하세요
SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE, COUNT(1) CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY CNT DESC
LIMIT 1;

SELECT MP.MEMBER_NAME
    , RR.REVIEW_TEXT
    , DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE MP
    INNER JOIN ( SELECT MEMBER_ID, COUNT(1) CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    ) RC ON MP.MEMBER_ID = RC.MEMBER_ID
    INNER JOIN REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;