-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
    INNER JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE >= '20220101' AND S.SALES_DATE < '20220201'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
    