-- 코드를 입력하세요
SELECT H.HISTORY_ID
    , CASE WHEN P.DISCOUNT_RATE THEN ROUND(C.DAILY_FEE * (1 - P.DISCOUNT_RATE * 0.01) * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1), 0)
    ELSE ROUND(C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1), 0) END AS FEE
FROM (SELECT *
    , CASE WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN '90일 이상'
    WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 30 THEN '30일 이상'
    WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 7 THEN '7일 이상' END AS DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) H
    INNER JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION = P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;
