-- 코드를 입력하세요
# SELECT TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') from MEMBER_PROFILE;

SELECT MEMBER_ID, MEMBER_NAME, GENDER,
DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
from MEMBER_PROFILE
where TLNO is not null and MONTH(DATE_OF_BIRTH) = '3' and GENDER = 'W'
order by MEMBER_ID;